[[categories]]

displayName = "Mathematics"
code = "MATH"
series = [
    "MATH-M-900",
    "MATH-M-999"
]

[[categories]]

displayName = "Computer Science"
code = "COMP"
series = [
    "COMP-M-999"
]

[[categories]]

displayName = "Iris"
code = "IRIS"
series = [
    "IRIS-S-1",
    "IRIS-S-900"
]
