[[categories]]

displayName = "Mathematics"
code = "MATH"
description = "Everyone's favorite subject"
series = [
    "MATH-M-900"
]

[[categories]]

displayName = "Iris"
code = "IRIS"
description = "All about Iris"
series = [
    "IRIS-S-1",
    "IRIS-S-900",
    "IRIS-S-900X"
]
