type = "series"
code = "IRIS-S-900X"
title = "Iris Test Series"
description = "Series testing Iris/Patchouli features"
authors = [
    "kyo"
]
tags = [ "iris", "testing" ]
prerequisites = [ "IRIS-S-1" ]
corequisites = [ "IRIS-S-900" ]

[[chapters]]

top_level = true
articles = [
    "introduction"
]

[[chapters]]

title = "Chapter 1: The first chapter"
articles = [
    "chapter-1/math",
    "chapter-1/code-blocks"
]

[[chapters]]

title = "Chapter 2: The second chapter"
articles = [
    "chapter-2/directives"
]

[[chapters]]

top_level = true
articles = [
    "appendix"
]
