type = "series"
code = "IRIS-S-1"
title = "Welcome to Iris!"
description = "An introduction to Iris"
authors = [
    "kyo"
]
tags = [ "iris" ]

[[chapters]]

top_level = true
articles = [
    "welcome",
    "characters",
    "acknowledgments"
]

[[chapters]]

title = "About the authors"
articles = [
    "authors/kyo"
]
