type = "series"
code = "COMP-M-999"
title = "Computer Science Glossary"
description = "Definitions of computer science terms"
authors = [
    "kyo"
]

[[chapters]]

title = "A"
articles = [
    "a/argument"
]

[[chapters]]

title = "C"
articles = [
    "c/c",
    "c/compiler",
    "c/computer",
    "c/computer-science",
    "c/cpp",
    "c/cpp-std"
]

[[chapters]]

title = "F"
articles = [
    "f/function"
]

[[chapters]]

title = "G"
articles = [
    "g/garbage-collector"
]

[[chapters]]

title = "H"
articles = [
    "h/heap-memory",
    "h/hello-world"
]

[[chapters]]

title = "M"
articles = [
    "m/memory",
    "m/memory-management"
]

[[chapters]]

title = "O"
articles = [
    "o/object",
    "o/object-oriented-programming"
]

[[chapters]]

title = "P"
articles = [
    "p/parameter",
    "p/pointer",
    "p/program",
    "p/programming-language"
]

[[chapters]]

title = "S"
articles = [
    "s/smart-pointer",
    "s/stack-memory",
    "s/syntax"
]

[[chapters]]

title = "V"
articles = [
    "v/variable"
]
