type = "series"
code = "IRIS-S-900"
title = "Iris Internals"
description = "Internal documentation for Iris and Patchouli"
authors = [
    "kyo"
]
tags = [ "iris" ]

[[chapters]]

top_level = true
articles = [
    "series-numbering",
    "patchouli",
    "tex"
]
