/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UserAccount {
  created: Generated<Timestamp>;
  email: string;
  family_name: string | null;
  given_name: string | null;
  id: Generated<string>;
}

export interface UserFederatedIdentity {
  created: Generated<Timestamp>;
  federated_id: string;
  id: Generated<number>;
  provider: string;
  user_id: string;
}

export interface DB {
  user_account: UserAccount;
  user_federated_identity: UserFederatedIdentity;
}
